version: "3"

services:
  db:
    image: daniellujan/oracle-db:latest
    container_name: sitas-oracle-db
    hostname: sitas-oracle-db
    environment:
      ORACLE_SID: MYCDB
      ORACLE_PDB: MYPDB
      ORACLE_PWD: oracle
      ORACLE_CHARACTERSET: AL32UTF8
      ORACLE_EDITION: EE
    ports:
      - "1521:1521"
      - "5500:5500"
    tty: true
    privileged: true
    volumes:
      - ./init-scripts:/opt/oracle/scripts/setup

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sitas-api
    hostname: sitas-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      JDBC_URL: jdbc:oracle:thin:@db:1521:MYCDB
      JDBC_USER: AIRLINE_ADMIN
      JDBC_PASSWORD: SITAS
